services:
  - type: web
    name: autocut-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: autocut-redis
          property: connectionString
      - key: FRONTEND_URL
        value: "https://your-vercel-domain.vercel.app"
    # Starting uvicorn
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"

  - type: worker
    name: autocut-celery-worker
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: autocut-redis
          property: connectionString
    # Starting Celery worker
    startCommand: "celery -A app.worker.celery_app worker --loglevel=info --concurrency=2"

  - type: redis
    name: autocut-redis
    ipAllowList: [] # Allow internal Render connections
    plan: free # or starter
